server:
  port: 8082

spring:
  application:
    name: logs-service
  data:
    mongodb:
      uri: mongodb://${SPRING_DATASOURCE_USERNAME:root}:${SPRING_DATASOURCE_PASSWORD:password}@${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:27017}/?ssl=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      database: ${SPRING_DATASOURCE_DATABASE:logs}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER:http://localhost:8080/api/v1/auth}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8080/api/v1/auth/.well-known/jwks.json}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
      schema:
        log: ${KAFKA_LOG_SCHEMA:log}

cors:
  origin: ${CORS_ORIGIN:http://localhost:3000}